[package]
name = "asap_deps_keyserver"
version = "0.2.0"
license = "MIT"
edition = "2018"
authors = [ "Callum Osmotherly <cosmotherly@atlassian.com>" ]
homepage = "https://bitbucket.org/atlassianlabs/rust-asap/"
repository = "https://bitbucket.org/atlassianlabs/rust-asap/"
description = "This is a dev-dependency of rust-asap."

[dependencies]
hyper = { version = "0.14.16", features = [ "server" ] }
reqwest = "0.11.9"
tokio = { version = "1.16.1", features = [ "full" ] }
