[package]
name = "asap_deps_keyserver"
version = "0.1.1"
license = "MIT"
edition = "2018"
authors = ["Callum Osmotherly <cosmotherly@atlassian.com>"]
homepage = "https://bitbucket.org/atlassianlabs/rust-asap/"
repository = "https://bitbucket.org/atlassianlabs/rust-asap/"
description = "This is a dev-dependency of rust-asap."

[dependencies]
hyper = "0.13"
tokio = { version = "0.2", features = ["full"] }
reqwest = "0.10"
