image: rust:latest

pipelines:
  default:
    - parallel:
        - step:
            name: Build and test
            script:
              - cd ./asap
              - cargo build
              - cargo test
        - step:
            name: Run benchmarks
            script:
              - cd ./asap
              - cargo bench
