[workspace]
members = ["support/keyserver"]

[package]
name = "asap"
readme = "README.md"
version = "0.1.0"
license = "MIT"
authors = ["acheronfail <acheronfail@gmail.com>"]
keywords = ["asap", "jwt", "api", "token", "authorisation"]
homepage = "https://bitbucket.org/acheronfail/rust-asap/"
repository = "https://bitbucket.org/acheronfail/rust-asap/"
description = "An implementation of ASAP for rust."

[dependencies]
# jsonwebtoken = "4"
serde_derive = "1"
serde_json = "1"
serde = "1"
chrono = "0.4"
reqwest = "0.8.6"
failure = "0.1.1"
failure_derive = "0.1.1"

# We use a fork of `jsonwebtoken - with the smallest change:
# It now returns the `Map<String, Value>` of the token's claims.
# See: https://github.com/Keats/jsonwebtoken/issues/53
[dependencies.jsonwebtoken]
git = "https://github.com/acheronfail/jsonwebtoken/"
branch = "feat/add-claims-map"
