use std::result::{Result as StdResult};
use failure::{Error, SyncFailure};

// A handy alias for `Result` that carries a generic error type.
pub type Result<T> = ::std::result::Result<T, Error>;

// The `jsonwebtoken` lib uses the deprecated `error_chain` lib for its error
// handling. This is a small fix so that the `failures` lib plays nicely with
// the errors generated by `error_chain`.
//
// See: https://github.com/rust-lang-nursery/failure/issues/109
pub trait ResultExt<T, E> {
    fn sync(self) -> StdResult<T, SyncFailure<E>>
    where
        Self: Sized,
        E: ::std::error::Error + Send + 'static;
}

impl<T, E> ResultExt<T, E> for StdResult<T, E> {
    fn sync(self) -> StdResult<T, SyncFailure<E>>
    where
        Self: Sized,
        E: ::std::error::Error + Send + 'static,
    {
        self.map_err(SyncFailure::new)
    }
}
