[package]
name = "asap-cli"
version = "0.1.0"
authors = ["cosmotherly <cosmotherly@atlassian.com>"]
homepage = "https://bitbucket.org/atlassianlabs/rust-asap/"
description = "A command line utility for generating ASAP tokens."

[dependencies]
asap = { path = "../" }
structopt = "0.2"
clap = "2"
directories = "1.0"
human-panic = "1.0"
failure = "0.1.1"
failure_derive = "0.1.1"
pem = "0.5.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[[bin]]
name = "asap"
path = "src/main.rs"
